M48
; DRILL file {KiCad 9.0.7+1} date 2026-05-16T13:21:04+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-16T13:21:04+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.300
%
G90
G05
T1
X48.82Y-81.81
X48.82Y-87.59
T2
X56.35Y-124.5
X69.05Y-124.5
M30
