M48
; DRILL file {KiCad 9.0.7+1} date 2026-05-16T13:43:24+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-16T13:43:24+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.300
%
G90
G05
T1
X119.57Y-78.22
X119.57Y-84.0
T2
X127.1Y-120.91
X139.8Y-120.91
M30
