M48
; DRILL file {KiCad 9.0.7+1} date 2026-05-25T12:13:52+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-25T12:13:52+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.300
%
G90
G05
T1
X140.62Y-52.08
X146.4Y-52.08
T2
X127.1Y-124.0
X139.8Y-124.0
M30
